### ISSUE TITLE
Import problems in "Move Group Python Interface"

### ISSUE THREAD

**Issue by whateverco** [ros-planning/moveit_tutorials#739]
### Description
the console meet "import error"

### Your environment
ROS Distro:melodic
OS Version: Ubuntu 18.04

### Steps to reproduce
In "Start RViz and MoveGroup node" , when i run the Python code directly in the other shell (rosrun moveit_tutorials move_group_python_interface_tutorial.py), i meet the problem.

### Backtrace or Console output
```Traceback (most recent call last):
  File "/home/hzx/ws_moveit/src/moveit_tutorials/doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py", line 47, in <module>
    import moveit_commander
  File "/opt/ros/melodic/lib/python2.7/dist-packages/moveit_commander/__init__.py", line 3, in <module>
    from .planning_scene_interface import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/moveit_commander/planning_scene_interface.py", line 37, in <module>
    from . import conversions
  File "/opt/ros/melodic/lib/python2.7/dist-packages/moveit_commander/conversions.py", line 45, in <module>
    import tf
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py", line 31, in <module>
    from .listener import Transformer, TransformListener, TransformerROS
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/listener.py", line 29, in <module>
    import numpy
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: /usr/lib/x86_64-linux-gnu/libblas.so.3: undefined symbol: gotoblas
```

**Comment by rhaschke** [comment]
Looks like you screwed your installation of `libblas`. Try to reinstall and check which other versions of `blas` you have installed. Googling the original error `undefined symbol: gotoblas` yields tons of suggestions!
This is definitely unrelated to MoveIt. Thus closing here.
