### ISSUE TITLE
Python argument types in     MoveGroupInterface.compute_cartesian_path(MoveGroupInterface, list, float, float) did not match C++ signature:

### ISSUE THREAD

**Issue by law1209** [ros-planning/moveit_tutorials#832]
### Description

When trying the moveit python interface tutorial as in:

https://moveit.github.io/moveit_tutorials/doc/move_group_python_interface/move_group_python_interface_tutorial.html
roslaunch panda_moveit_config demo.launch
rosrun moveit_tutorials move_group_python_interface_tutorial.py

the move_group_python_interface_tutorial encounters an error as in the step III Press `Enter` to plan and display a Cartesian path .

### Your environment
* ROS Distro: noetic
* OS Version: 20.04
* Source build
https://github.com/moveit/moveit_tutorials.git -b master

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.

### Expected behaviour
Tell us what should happen

### Backtrace or Console output

Traceback (most recent call last):
  File "/home/robot/ws_moveit/devel/lib/moveit_tutorials/move_group_python_interface_tutorial.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/robot/ws_moveit/src/moveit_tutorials/doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py", line 538, in <module>
    main()
  File "/home/robot/ws_moveit/src/moveit_tutorials/doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py", line 500, in main
    cartesian_plan, fraction = tutorial.plan_cartesian_path()
  File "/home/robot/ws_moveit/src/moveit_tutorials/doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py", line 280, in plan_cartesian_path
    (plan, fraction) = move_group.compute_cartesian_path(
  File "/home/robot/ws_moveit/src/moveit/moveit_commander/src/moveit_commander/move_group.py", line 676, in compute_cartesian_path
    (ser_path, fraction) = self._g.compute_cartesian_path(
Boost.Python.ArgumentError: Python argument types in
    MoveGroupInterface.compute_cartesian_path(MoveGroupInterface, list, float, float)
did not match C++ signature:
    compute_cartesian_path(moveit::planning_interface::MoveGroupInterfaceWrapper {lvalue}, boost::python::list, double, bool, moveit::py_bindings_tools::ByteString)
    compute_cartesian_path(moveit::planning_interface::MoveGroupInterfaceWrapper {lvalue}, boost::python::list, double, bool)

Use [gist.github.com](gist.github.com) to copy-paste the console output or segfault backtrace using gdb.

**Comment by law1209** [comment]
Solution:
File:~/ws_moveit/src/moveit_tutorials/doc/move_group_python_interface/scripts/move_group_python_interface_tutorial.py
Line 281, delete the param jump_threshod (0.0)

**Comment by rhaschke** [comment]
Please file a PR with the suggested change.

**Comment by rhaschke** [comment]
> Please file a PR with the suggested change.

Done: c98147c6d30cadfa0deb4677c922cfcff4b75f47
